### PR TITLE
update jts-core to latest

### PR DESCRIPTION
**Pull request by lockwobr**
In jts 1.17 there was a breaking change to the api, this pr addresses this.

### CODE REVIEW

**Comment by bjornharrtell** [comment]
Thanks that looks sensible.

**Comment by go0ty** [comment]
Would love to see this merged!

**Comment by bjornharrtell** [comment]
@go0ty it's your lucky day, merged and released into 0.15.0 and 0.16.0 (with upgraded jackson deps).

**Comment by go0ty** [comment]
Much appreciated!

**Pull request merged**
